/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CAAYcyclic.PlannerClient.view.panel.bar;

import CAAYcyclic.PlannerClient.enumeration.ApplicationColor;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Amos
 */
public final class MainSideBarPanel extends JPanel {

    /**
     * Creates new form MainSideBarPanel
     */
    
    private JButton selectedButton;
    
    public MainSideBarPanel() {
        initComponents();
        highlightButton(dashBtn);
    }

    public JButton getDashBtn() {
        return dashBtn;
    }

    public JButton getActivitiesBtn() {
        return activitiesBtn;
    }

    public JButton getMaintBtn() {
        return maintBtn;
    }
    
    public void highlightButton(JButton button) {
        
        if (selectedButton != null){
            selectedButton.setBorderPainted(false);
            selectedButton.setBackground(null);
            selectedButton.setFont(button.getFont().deriveFont(Font.PLAIN));
        }
        
        button.setBorderPainted(true);
        button.setBackground(ApplicationColor.accentColor.value);
        button.setFont(button.getFont().deriveFont(Font.BOLD));
        selectedButton = button;
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashBtn = new javax.swing.JButton();
        activitiesBtn = new javax.swing.JButton();
        maintBtn = new javax.swing.JButton();

        setBackground(ApplicationColor.primaryColor.value);

        dashBtn.setBackground(ApplicationColor.primaryColor.value);
        dashBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        dashBtn.setForeground(new java.awt.Color(255, 255, 255));
        dashBtn.setText("DashBoard");
        dashBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0), javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 3, new java.awt.Color(242, 241, 241))));
        dashBtn.setBorderPainted(false);
        dashBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        dashBtn.setMargin(new java.awt.Insets(0, 10, 0, 10));
        dashBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashBtnActionPerformed(evt);
            }
        });

        activitiesBtn.setBackground(ApplicationColor.primaryColor.value);
        activitiesBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        activitiesBtn.setForeground(new java.awt.Color(255, 255, 255));
        activitiesBtn.setText("Activities");
        activitiesBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0), javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 3, new java.awt.Color(242, 241, 241))));
        activitiesBtn.setBorderPainted(false);
        activitiesBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        maintBtn.setBackground(ApplicationColor.primaryColor.value);
        maintBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        maintBtn.setForeground(new java.awt.Color(255, 255, 255));
        maintBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0), javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 3, new java.awt.Color(242, 241, 241))));
        maintBtn.setBorderPainted(false);
        maintBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
            .addComponent(activitiesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(maintBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(dashBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activitiesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dashBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activitiesBtn;
    private javax.swing.JButton dashBtn;
    private javax.swing.JButton maintBtn;
    // End of variables declaration//GEN-END:variables
}
